"gitlabUrl": "https://gitlab.com"
"rbac":
  "clusterWideAccess": false
  "create": true
  "podSecurityPolicy":
    "enabled": false
    "resourceNames":
    - "gitlab-runner"
  "rules":
  - "apiGroups":
    - ""
    "resources":
    - "pods"
    - "secrets"
    - "configmaps"
    "verbs":
    - "get"
    - "list"
    - "watch"
    - "create"
    - "patch"
    - "delete"
    - "update"
  - "apiGroups":
    - ""
    "resources":
    - "pods/exec"
    - "pods/attach"
    "verbs":
    - "create"
    - "patch"
    - "delete"
  - "apiGroups":
    - "apps"
    "resources":
    - "deployments"
    "verbs":
    - "get"
    - "list"
    - "watch"
    - "create"
    - "update"
    - "patch"
    - "delete"
"revisionHistoryLimit": 3
"runnerRegistrationToken": "glrt-n9qgipWsAEftuvn88GBMoW86MQpwOjE5dTNpcQp0OjMKdTpqNWlsdBg.01.1j0vadks8"
